### ISSUE TITLE
quick clicks will lose data

### ISSUE THREAD

**Issue by xingstarx** [GoodieBag/Pinview#1]
I found some problem,On some android devices, quick clicks will lose data

For example, I quickly enter 1234, View on the display may be 14, this is what happens to me on Samsung SM-G9350(android 6.0.1)

I need your help

**Comment by Vatican-Cameos** [comment]
May I know what keyboard you are using on samsung ?

**Comment by xingstarx** [comment]
In my study, the problem lies on Samsung keyboard, when I use Google keyboard,that show normal.

Thank you for your help

**Comment by Vatican-Cameos** [comment]
Yes I reckoned the same and was going to tell you the same thing. The problem is that different keyboards handle events  differently. Customised keyboards are hard to handle with. So we optimised it for google keyboards since its the most used all around and other 3rd party keyboards are also based on this. It's working with most of the keyboards.
We plan to find a work around for this in the next release.  :simple_smile:
